### PR TITLE
Fix Tooltip Rendering

### LINKED ISSUE #1: Tooltips do not render correctly when there are multiple entitys within a tile.
Here's an example with both fire and the player in a single tile.

Screen Shot 2021-03-14 at 11 36 58 AM

Fire and a potion of fire:

Screen Shot 2021-03-14 at 11 38 22 AM

### PR DESCRIPTION
**Pull request by madrury**
Fixes https://github.com/madrury/rusty-rogue/issues/1.

Instead of fussing over line-by-line padding, we instead simply compute the size of and then render a background rectangle before rendering any information into the tooltip.

We also sort the tooltips in order of increasing length to make for a better look.

## Examples
Screen Shot 2024-01-31 at 8 20 11 PM

Screen Shot 2024-01-31 at 8 51 16 PM

Screen Shot 2024-01-31 at 8 51 28 PM

Screen Shot 2024-01-31 at 9 01 27 PM

### CODE REVIEW

File: rogue/src/terrain_spawners/water.rs [hunk 1]
```diff
@@ -105,7 +105,7 @@ pub fn shallow_water(ecs: &mut World, x: i32, y: i32, fgcolor: RGB, bgcolor: RGB
             glyph: rltk::to_cp437('~'),
             fg: fgcolor,
             bg: bgcolor,
-            order: 3,
```
Comment (madrury) [inline rogue/src/terrain_spawners/water.rs:108]: Just a small opportunistic bugfix.

Grass and water was set to the same render order, and this seemed to lead to non-deterministic ordering, sometimes the grass would render, sometimes it would be masked by the water. We want to see the sweet, sweet grass.

File: rogue/src/gui.rs [hunk 2]
```diff
@@ -337,59 +338,59 @@ fn draw_tooltips(ecs: &World, ctx: &mut Rltk) {
...
         let idx = map.xy_idx(pos.x, pos.y);
         if pos.x == mpos.0 && pos.y == mpos.1 && map.visible_tiles[idx] {
-            tooltip.push(name.name.to_string());
+            tooltips.push(name.name.to_string());
             status_indicators.push(get_status_indicators(&ecs, &entity))
         }
     }
+    // Sort the tooltip, status pairs by increasing length of the tooltip. This
+    // looks best when rendered.
+    let mut both: Vec<(String, Vec<StatusIndicatorGlyph>)> = tooltips
```
Comment (madrury) [inline rogue/src/gui.rs:352]: De-rusting my rust. 🥁

**Review by axiomabsolute — COMMENTED** [review]
🚀
